json.email @user.email
json.password @user.password
json.password_confirmation @user.password_confirmation
json.first_name @user.first_name
json.last_name @user.last_name
json.phone_number @user.phone_number
json.city @user.city
json.state @user.state
json.country @user.country
json.device_id @user.device_id
json.device_type @user.device_type
json.user_id @auth_tokan.user_id
json.tokan @auth_tokan.tokan